[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0a0e1a"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false